### ISSUE TITLE
Errors in use - $roll pool X, $option

### ISSUE THREAD

**Issue by ToferC** [dbisdorf/cortex-discord#6]
Hi Dan, 

First this is a super little bot. Thank you!

My players and I are just starting to use it and and I wanted to let you know about some errors in the basic functionality.

$pool roll doom (or any pool name)
$option (for help)

The error received is: `Oops. A software error interrupted this command.`

Thanks and all the best,

C

**Comment by dbisdorf** [comment]
Thanks for filing this! I can't reproduce the $pool error on my end. Could you do the following;

- Run "$info" to show the state of your game.

- Run "$pool roll doom" to generate the error.

Then screenshot the whole thing and attach it here.

Thanks again!

**Comment by ToferC** [comment]
For sure! Here you go. I've also cleared the pool and tried it with several new pools and I get the same error. I will also try removing and re-adding the bot if the info isn't useful. 
![Screenshot_20200926-143842_Discord](https://user-images.githubusercontent.com/6226762/94347919-45748500-0006-11eb-8644-93b6895a8c64.jpg)

**Comment by dbisdorf** [comment]
Thanks, this is a big help. Hopefully between this and my log files I should be able to work this out.

**Comment by dbisdorf** [comment]
I've just pushed out a release that I hope will fix both the $option bug and the $pool bug. Give it a shot at your end and let me know how it looks.

**Comment by ToferC** [comment]
Just tried it out and it works great! Thanks so much again for such a handy tool!
